#!/usr/bin/env php
<?php
/**
 * Phreak! Installer
 */
echo "\n################# Phreak! #################\n";
echo "Installer will run a few tasks now...\n";
echo "Settings file/directory permissions...\n";
setPermissions([
    "storage"=>"0777",
    "storage/cache/smarty"=>"0777",
    "storage/cache/stash"=>"0777",
    "storage/languages"=>"0777",
    "storage/logs"=>"0777",
    "storage/uploads"=>"0777"
]);
echo "Copying sample configs...\n";
copyFiles([
    "config/system.php.sample"=>"config/system.php",
    "config/cache.php.sample"=>"config/cache.php",
    "config/database.php.sample"=>"config/database.php",
    "config/modules.php.sample"=>"config/modules.php"            
]);
echo "\nPhreak! has been successfuly installed!\n";
echo "################ Enjoy! ################\n";

    /**
     * Sets the correct permission for the files and directories listed in the extra section.
     * @param array $paths the paths (keys) and the corresponding permission octal strings (values)
     */
    function setPermissions(array $paths) {
        foreach ($paths as $path => $permission) {
            echo "chmod('$path', $permission)...";
            if (is_dir($path) || is_file($path)) {
                try {
                    if (chmod($path, octdec($permission))) {
                        echo "done.\n";
                    };
                } catch (\Exception $e) {
                    echo $e->getMessage() . "\n";
                }
            } else {
                echo "file not found.\n";
            }
        }
    }

    /**
     * Copy files to specified locations.
     * @param array $paths The source files paths (keys) and the corresponding target locations
     * for copied files (values). Location can be specified as an array - first element is target
     * location, second defines whether file can be overwritten (by default method don't overwrite
     * existing files).
     * @since 2.0.5
     */
     function copyFiles(array $paths) {
        foreach ($paths as $source => $target) {
            // handle file target as array [path, overwrite]
            $target = (array) $target;
            echo "Copying file $source to $target[0] - ";

            if (!is_file($source)) {
                echo "source file not found.\n";
                continue;
            }

            if (is_file($target[0]) && empty($target[1])) {
                echo "target file exists - skip.\n";
                continue;
            } elseif (is_file($target[0]) && !empty($target[1])) {
                echo "target file exists - overwrite - ";
            }

            try {
                if (!is_dir(dirname($target[0]))) {
                    mkdir(dirname($target[0]), 0777, true);
                }
                if (copy($source, $target[0])) {
                    echo "done.\n";
                }
            } catch (\Exception $e) {
                echo $e->getMessage() . "\n";
            }
        }
    }

